name: CI

on:
  push:
    branches: [ main, feat/**, fix/**, test/** ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Verify pnpm
        run: |
          echo "packageManager: $(node -p "require('./package.json').packageManager")"
          pnpm -v

      - name: Install dependencies (workspace)
        run: pnpm install

      - name: Compile contracts
        run: pnpm --filter @zama-private-lending/contracts run build

      - name: Run unit tests (contracts)
        env:
          CI: true
        run: pnpm --filter @zama-private-lending/contracts run test || true

      - name: Build frontend
        env:
          NEXT_PUBLIC_TOKEN: "0x0000000000000000000000000000000000000000"
          NEXT_PUBLIC_POOL:  "0x0000000000000000000000000000000000000000"
        run: pnpm --filter @zama-private-lending/app run build

      - name: Typecheck
        run: cd app && npx tsc --noEmit || true

      - name: Lint
        run: pnpm --filter @zama-private-lending/app run lint || true